[project]
name = "flareio-cli"
version = "0.1.0"
description = "CLI interface for the flare.io API"
readme = "README.md"
authors = [
    { name = "Alexandre Viau", email = "alexandre.viau@flare.io" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
flareio = "flareio_cli:main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
