[project]
name = "flareio-cli"
version = "0.2.0"
description = "CLI interface for the flare.io API"
readme = "README.md"
authors = [
    { name = "Alexandre Viau", email = "alexandre.viau@flare.io" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
flareio = "flareio_cli:cli.main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ty>=0.0.15",
]
